PREFIX : <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
CONSTRUCT {?s ?p ?o}
WHERE {
  {
    VALUES ?s {:CID313}
    ?s ?p ?o .
    FILTER( ?p != sio:CHEMINF_000455 )
  }UNION{
    VALUES ?o {:CID313}
    VALUES ?p {
      sio:CHEMINF_000477
      obo:RO_0000057
      sio:is-attribute-of }
    ?s ?p ?o .
  }
}
# not include (?:has_parent|CHEMINF_0004(?:55|61|62|80))
